### PR TITLE
Skip/force refresh for completed/archived games

### PR DESCRIPTION
**Pull request by disaster2395**
**Reason**:
Since I'm keeping all games I'm currently playing/have played/not interested anymore, games count only increasing. Usually I mark "finished" games as archived so I won't get update notifications for them.
This PR allow to speed up refresh process with optional force-refresh via dropdown menu.

**Added**:
- boolean option "Refresh if archived" similar to "Refresh if completed" under "Refresh' settings
- few refresh buttons in "Refresh!" dropdown list
  - "Full Refresh (incl. completed)" - if "Refresh if completed" is unchecked
  - "Full Refresh (incl. archived)" - if "Refresh if archived" is unchecked
  - "Full Refresh (incl. everything)" - if both unchecked at same time

### CODE REVIEW

**Comment by FaceCrap** [comment]
Feels a bit overcomplicated... the same could have been accomplished with just adding a checkbox to include/exclude Archived games in the sidebar. 
Don't see why it also would need options on the Refresh button context menu. This type of preference is not one you'll likely change often. 
So it wouldn't be too much of an issue to just toggle a checkmark for the occasional times you'd actually want to include/exclude one or the other or both.
Adding them as context options would nullify the reason they would exist as a preference setting in the sidebar.

**Comment by At-Libitum** [comment]
Here's an idea. Make the `Full Refresh` context item keep behaving as-is but make it so it can also open a submenu to toggle the same settings as in the sidebar.
So, depending on the state of the items in the submenu (checked or not), the `Full Refresh` item either excludes or includes `Completed` and/or `Archived` games.

**Comment by At-Libitum** [comment]
> These are conditions for button to appear. E.g. "Full Refresh (incl. completed)" will only appear in dropdown if "Refresh if completed" is unchecked - normally ignored during refresh, but here is the button.

Ah, that paints a whole different picture, from the previous posts I assumed they would always be there. And then I would have agreed with @FaceCrap, but if they only show when the buttons are unchecked it's a different thing.

**Review by Willy-JL — APPROVED** [review]
LGTM! though it was a bit overkill, but hiding the options based on what you have in settings makes sense

**Pull request merged**
