### PR TITLE
Detect missing tags script

### PR DESCRIPTION
**Pull request by r37r05p3C7**
Script detects missing tags by parsing the Latest Updates page using Selenium. It's not user-facing and is meant to be used like a pre-commit hook. As far as I know, this is the best way to parse all public tags at the moment.

image

### CODE REVIEW

**Comment by Willy-JL** [comment]
This could definitely come in useful, nice. Is there any particular reason why this wouldn't work with requests or aiohttp?

**Comment by FaceCrap** [comment]
Would this page be any help to detect missing tags?

https://f95zone.to/tags/

**Comment by FaceCrap** [comment]
> "popular tags" implies subset of all tags,

That's what I thought too the first time I found that page, yet the missing ones you added are all listed... 🤷🏼‍♂️

**Comment by Willy-JL** [comment]
Thank you, this is perfect! May I also suggest `sys.exit(0)` for success and `sys.exit(1)` for missing tags? Then it could be automated with a GitHub action (I'm not asking to make that workflow, just the exit codes on the script)

**Review by Willy-JL — APPROVED** [review]
Thanks!

**Pull request merged**
